import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import Footer from "./Footer/Footer";
import { Assets } from "@/Assets/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Qovex Studio",
  description: "Generated by Qovex Studio",
  icons: {
    icon: "/Logo.svg",  // or use /logo.png or /logo.svg
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  max-w-[1500px] mx-auto bg-white`}
      >

        <div className="bg-white">
        <Header/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
